# Generated by Django 4.2 on 2026-04-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeenGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.CharField(blank=True, help_text='Your daily deen goal', max_length=255)),
                ('weekly_target', models.CharField(blank=True, help_text='Your weekly deen goal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deen_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deen Goal',
                'verbose_name_plural': 'Deen Goals',
            },
        ),
        migrations.CreateModel(
            name='DeenEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('salah', 'Salah (Prayer)'), ('quran', 'Quran Recitation'), ('dhikr', 'Dhikr'), ('dua', 'Dua (Supplication)'), ('charity', 'Charity'), ('knowledge', 'Islamic Knowledge'), ('other', 'Other')], default='salah', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True, help_text='Personal reflection or notes')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deen_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deen Entry',
                'verbose_name_plural': 'Deen Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
