# Generated by Django 4.2 on 2026-04-18 00:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cp_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CP Streak',
                'verbose_name_plural': 'CP Streaks',
            },
        ),
        migrations.CreateModel(
            name='CPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('exercise', 'Exercise'), ('diet', 'Diet'), ('sleep', 'Sleep'), ('meditation', 'Meditation'), ('reading', 'Reading'), ('goal', 'Goal'), ('other', 'Other')], default='goal', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CP Entry',
                'verbose_name_plural': 'CP Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
